const buyersList = [
  {
    id: 1,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APRIL, 2024",
    ticketType: "VIP",
    price: "$200",
    ticketId: "517365716",
    payment: "Paypal",
  },
  {
    id: 2,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APRIL, 2024",
    ticketType: "VIP",
    price: "$200",
    ticketId: "517365716",
    payment: "Paypal",
  },
  {
    id: 3,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APRIL, 2024",
    ticketType: "STANDARD",
    price: "$200",
    ticketId: "517365716",
    payment: "Paypal",
  },
  {
    id: 4,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APRIL, 2024",
    ticketType: "VIP",
    price: "$200",
    ticketId: "517365716",
    payment: "Paypal",
  },
  {
    id: 5,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APRIL, 2024",
    ticketType: "WEEKENDER",
    price: "$200",
    ticketId: "517365716",
    payment: "Paypal",
  },
  {
    id: 6,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APRIL, 2024",
    ticketType: "VIP",
    price: "$200",
    ticketId: "517365716",
    payment: "Paypal",
  },
  {
    id: 7,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APRIL, 2024",
    ticketType: "VIP",
    price: "$200",
    ticketId: "517365716",
    payment: "Paypal",
  },
  {
    id: 8,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APRIL, 2024",
    ticketType: "STANDARD",
    price: "$200",
    ticketId: "517365716",
    payment: "Paypal",
  },
  {
    id: 9,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APRIL, 2024",
    ticketType: "VIP",
    price: "$200",
    ticketId: "517365716",
    payment: "Paypal",
  },
  {
    id: 10,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APRIL, 2024",
    ticketType: "WEEKENDER",
    price: "$200",
    ticketId: "517365716",
    payment: "Paypal",
  },
  {
    id: 11,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APRIL, 2024",
    ticketType: "VIP",
    price: "$200",
    ticketId: "517365716",
    payment: "Paypal",
  },
  {
    id: 12,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APRIL, 2024",
    ticketType: "STANDARD",
    price: "$200",
    ticketId: "517365716",
    payment: "Paypal",
  },
  {
    id: 13,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APRIL, 2024",
    ticketType: "VIP",
    price: "$200",
    ticketId: "517365716",
    payment: "Paypal",
  },
  {
    id: 14,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APRIL, 2024",
    ticketType: "WEEKENDER",
    price: "$200",
    ticketId: "517365716",
    payment: "Paypal",
  },
];

export { buyersList };
