const eventsList = [
  {
    id: 1,
    status: "Online",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Concert",
    reviews: "4.3",
  },
  {
    id: 2,
    status: "Upcoming",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Community Events",
    reviews: "4.3",
  },
  {
    id: 3,
    status: "Online",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Convention",
    reviews: "4.3",
  },
  {
    id: 4,
    status: "Online",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Tradeshow",
    reviews: "4.3",
  },
  {
    id: 5,
    status: "Cancel",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Festival",
    reviews: "4.3",
  },
  {
    id: 6,
    status: "Online",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Concert",
    reviews: "4.3",
  },
  {
    id: 7,
    status: "Online",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Concert",
    reviews: "4.3",
  },
  {
    id: 8,
    status: "Upcoming",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Concert",
    reviews: "4.3",
  },
  {
    id: 9,
    status: "Online",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Concert",
    reviews: "4.3",
  },
  {
    id: 10,
    status: "Cancel",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Concert",
    reviews: "4.3",
  },
  {
    id: 11,
    status: "Online",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Concert",
    reviews: "4.3",
  },
  {
    id: 12,
    status: "Online",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Concert",
    reviews: "4.3",
  },
  {
    id: 13,
    status: "Upcoming",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Community Events",
    reviews: "4.3",
  },
  {
    id: 14,
    status: "Online",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Convention",
    reviews: "4.3",
  },
  {
    id: 15,
    status: "Online",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Tradeshow",
    reviews: "4.3",
  },
  {
    id: 16,
    status: "Cancel",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Festival",
    reviews: "4.3",
  },
  {
    id: 17,
    status: "Online",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Concert",
    reviews: "4.3",
  },
  {
    id: 18,
    status: "Online",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Concert",
    reviews: "4.3",
  },
  {
    id: 19,
    status: "Upcoming",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Concert",
    reviews: "4.3",
  },
  {
    id: 20,
    status: "Online",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Concert",
    reviews: "4.3",
  },
  {
    id: 21,
    status: "Cancel",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Concert",
    reviews: "4.3",
  },
  {
    id: 22,
    status: "Online",
    name: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    date: "16 APR 2024",
    time: "09:00 AM",
    sale: "53",
    capacity: "300",
    price: "$203",
    type: "Concert",
    reviews: "4.3",
  },
];

export { eventsList };
