const historyList = [
  {
    id: 1,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    eventStatus: "ONLINE",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    status: "Paid",
    by: "Black Mamba",
    time: "10:00 PM",
    date: "16 APRIL, 2024",
    ticketType: "VIP",
    price: "$200",
    ticketId: "517365716",
    transactionId: "#15351",
    qty: "01",
    payment: "Paypal",
  },
  {
    id: 2,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    eventStatus: "OFFLINE",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    status: "Pending",
    by: "Black Mamba",
    time: "10:00 PM",
    date: "16 APRIL, 2024",
    ticketType: "VIP",
    price: "$200",
    ticketId: "517365716",
    transactionId: "#15351",
    qty: "01",
    payment: "Paypal",
  },
  {
    id: 3,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    eventStatus: "CANCEL",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    status: "Cancel",
    by: "Black Mamba",
    time: "10:00 PM",
    date: "16 APRIL, 2024",
    ticketType: "STANDARD",
    price: "$200",
    ticketId: "517365716",
    transactionId: "#15351",
    qty: "01",
    payment: "Paypal",
  },
  {
    id: 4,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    eventStatus: "ONLINE",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    status: "Refund",
    by: "Black Mamba",
    time: "10:00 PM",
    date: "16 APRIL, 2024",
    ticketType: "VIP",
    price: "$200",
    ticketId: "517365716",
    transactionId: "#15351",
    qty: "01",
    payment: "Paypal",
  },
  {
    id: 5,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    eventStatus: "-",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    status: "-",
    by: "Black Mamba",
    time: "10:00 PM",
    date: "16 APRIL, 2024",
    ticketType: "-",
    price: "$200",
    ticketId: "-",
    transactionId: "-",
    qty: "01",
    payment: "-",
  },
  {
    id: 6,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    eventStatus: "CANCEL by Admin",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    status: "-",
    by: "Black Mamba",
    time: "10:00 PM",
    date: "16 APRIL, 2024",
    ticketType: "-",
    price: "$200",
    ticketId: "-",
    transactionId: "-",
    qty: "01",
    payment: "-",
  },
  {
    id: 7,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    eventStatus: "-",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    status: "Pending",
    by: "Black Mamba",
    time: "10:00 PM",
    date: "16 APRIL, 2024",
    ticketType: "-",
    price: "$200",
    ticketId: "-",
    transactionId: "#15351",
    qty: "01",
    payment: "Paypal",
  },
  {
    id: 8,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    eventStatus: "OFFLINE",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    status: "Pending",
    by: "Black Mamba",
    time: "10:00 PM",
    date: "16 APRIL, 2024",
    ticketType: "STANDARD",
    price: "$200",
    ticketId: "517365716",
    transactionId: "#15351",
    qty: "01",
    payment: "Paypal",
  },
  {
    id: 9,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    eventStatus: "CANCEL",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    status: "Cancel",
    by: "Black Mamba",
    time: "10:00 PM",
    date: "16 APRIL, 2024",
    ticketType: "VIP",
    price: "$200",
    ticketId: "517365716",
    transactionId: "#15351",
    qty: "01",
    payment: "Paypal",
  },
  {
    id: 10,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    eventStatus: "ONLINE",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    status: "Refund",
    by: "Black Mamba",
    time: "10:00 PM",
    date: "16 APRIL, 2024",
    ticketType: "WEEKENDER",
    price: "$200",
    ticketId: "517365716",
    transactionId: "#15351",
    qty: "01",
    payment: "Paypal",
  },
  {
    id: 11,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    eventStatus: "CANCEL",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    status: "Cancel",
    by: "Black Mamba",
    time: "10:00 PM",
    date: "16 APRIL, 2024",
    ticketType: "VIP",
    price: "$200",
    ticketId: "517365716",
    transactionId: "#15351",
    qty: "01",
    payment: "Paypal",
  },
  {
    id: 12,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    eventStatus: "-",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    status: "-",
    by: "Black Mamba",
    time: "10:00 PM",
    date: "16 APRIL, 2024",
    ticketType: "STANDARD",
    price: "$200",
    ticketId: "517365716",
    transactionId: "#15351",
    qty: "01",
    payment: "Paypal",
  },
  {
    id: 13,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    eventStatus: "ONLINE",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    status: "Paid",
    by: "Black Mamba",
    time: "10:00 PM",
    date: "16 APRIL, 2024",
    ticketType: "VIP",
    price: "$200",
    ticketId: "517365716",
    transactionId: "#15351",
    qty: "01",
    payment: "Paypal",
  },
  {
    id: 14,
    name: "John Doe",
    email: "emailaddress@gmail.com",
    eventName: "D` BROWN CAPITALISM",
    eventStatus: "ONLINE",
    location: "Alt-Moabit 41, Neuburg, Freistaat Bayern",
    status: "Paid",
    by: "Black Mamba",
    time: "10:00 PM",
    date: "16 APRIL, 2024",
    ticketType: "WEEKENDER",
    price: "$200",
    ticketId: "517365716",
    transactionId: "#15351",
    qty: "01",
    payment: "Paypal",
  },
];

export { historyList };
