const userTransactions = [
  {
    id: 1,
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    date: "16 APRIL, 2024",
    time: "10:00 PM",
    type: "Ticket Buy",
    price: "$200",
    invoiceId: "517365716",
    payment: "Paypal",
  },
  {
    id: 2,
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    date: "16 APRIL, 2024",
    time: "10:00 PM",
    type: "Review",
    price: "-",
    invoiceId: "-",
    payment: "-",
  },
  {
    id: 3,
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    date: "16 APRIL, 2024",
    time: "10:00 PM",
    type: "Ticket Buy",
    price: "$200",
    invoiceId: "517365716",
    payment: "Paypal",
  },
  {
    id: 4,
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    date: "16 APRIL, 2024",
    time: "10:00 PM",
    type: "Refund",
    price: "$200",
    invoiceId: "517365716",
    payment: "Paypal",
  },
  {
    id: 5,
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",

    date: "16 APRIL, 2024",
    time: "10:00 PM",
    type: "Ticket Buy",
    price: "$200",
    invoiceId: "517365716",
    payment: "Paypal",
  },
  {
    id: 6,
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    date: "16 APRIL, 2024",
    time: "10:00 PM",
    type: "Ticket Buy",
    price: "$200",
    invoiceId: "517365716",
    payment: "Paypal",
  },
  {
    id: 7,
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    date: "16 APRIL, 2024",
    time: "10:00 PM",
    type: "Ticket Buy",
    price: "$200",
    invoiceId: "517365716",
    payment: "Paypal",
  },
  {
    id: 8,
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    date: "16 APRIL, 2024",
    time: "10:00 PM",
    type: "Refund",
    price: "$200",
    invoiceId: "517365716",
    payment: "Paypal",
  },
  {
    id: 9,
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    date: "16 APRIL, 2024",
    time: "10:00 PM",
    type: "Ticket Buy",
    price: "$200",
    invoiceId: "517365716",
    payment: "Paypal",
  },
  {
    id: 10,
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    date: "16 APRIL, 2024",
    time: "10:00 PM",
    type: "Review",
    price: "-",
    invoiceId: "-",
    payment: "-",
  },
  {
    id: 11,
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    date: "16 APRIL, 2024",
    time: "10:00 PM",
    type: "Ticket Buy",
    price: "$200",
    invoiceId: "517365716",
    payment: "Paypal",
  },
  {
    id: 12,
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    date: "16 APRIL, 2024",
    time: "10:00 PM",
    type: "Refund",
    price: "$200",
    invoiceId: "517365716",
    payment: "Paypal",
  },
  {
    id: 13,
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    date: "16 APRIL, 2024",
    time: "10:00 PM",
    type: "Ticket Buy",
    price: "$200",
    invoiceId: "517365716",
    payment: "Paypal",
  },
  {
    id: 14,
    eventName: "D` BROWN CAPITALISM",
    by: "Black Mamba",
    date: "16 APRIL, 2024",
    time: "10:00 PM",
    type: "Review",
    price: "-",
    invoiceId: "-",
    payment: "-",
  },
];

export { userTransactions };
